### PR TITLE
New removeAll function to empty pool of all workers

### PR DESCRIPTION
**Pull request by smugryan**
Awesome npm module! I've used it for a few weeks and it's exactly what I need to manage dozens of long-lived processes. 

I ran into an issue with processes that are spawned not dying when my main node.js is killed. So I added this function to kill all the processes that have been added to the pool at once. Just a simple helper function, nothing fancy.

Let me know what you think and if there's anything you'd change. I've tested it with my code and it works with no problems.

### CODE REVIEW

**Comment by smugryan** [comment]
Hi, any comments on my pull request? I'd love to get it into the NPM module so my company's Ops team can pull from there as opposed to using a custom version that I supply them. Thanks!

**Comment by baryshev** [comment]
Hi, sorry for the long response. There is one thing that confuses me in removeAll method. It can not remove resources that have not been returned to the pool through a release method, because pool have not references on these resources. I see the only way to do it - add an index of all resources to the pool object. I'll try to do it.

**Comment by baryshev** [comment]
But one more thing. Destruction of resources that have not been returned to the pool can lead to the application crash because they can be destroyed during use.

**Comment by baryshev** [comment]
I merged your commit with some changes, but still thinking.

**Comment by smugryan** [comment]
Awesome, thanks! I see what you mean about removing resources that haven't been returned to the pool. I'm wondering how an application could tell the pool to remove all processes. Maybe a function like killAll() that took a callback handler that was called only when all processes in the pool were actually killed?

**Pull request merged**
